const phoneBrands = [
    "Apple",
    "Tecno",
    "Samsung",
    "Lenovo",
    "Itel",
    "Infinix",
    "Huawei",
    "OPPO",
    "Nokia",
    "Vivo",
    "OnePlus",
    "Motorola",
    "Sony",
    "Alcatel Mobile",
    "ZTE",
    "Honor",
    "Micromax Informatics",
    "Fairphone",
    "Intex",
    "Acer",
    "Palm",
    "LeEco",
    "HTC",
    "Asus",
    "BenQ",
    "BlackBerry",
    "Gionee",
    "Google",
    "LG",
    "Microsoft",
    "Xiaomi",
    "Innjoo",
  ]

  export default phoneBrands;