const productsData = [
  {
    id: 1,
    displayName: "Victor",
    sellersId: "3456789",
    phoneNumber: "08152038183",
    backcamera: "23",
    battery: "4000",
    brand: "Apple",
    color: "Red",
    frontcamera: "30",
    newness: "new",
    price: "130000",
    headline: "iphone 12 pro max",
    ramsize: "6",
    screensize: "5",
    simslot: "Yes",
    storage: "512",
    sub_category: "phone",
    category: "mobile_devices",
    transaction_mode: "sell",
    imageUrls: [],
    numberOfViews: 374,
    dateAdded: new Date().getTime(),
    tags: ["phone", "iphone", "pro max"],
  },
  {
    id: 35,
    sellersId: "3456789",
    displayName: "Lisa",
    phoneNumber: "08152038183",
    numberOfViews: 670,
    transaction_mode: "auction",
    category: "fashion_accessories",
    headline: "Nevenka Women Leather Handbag",
    sub_category: "Bag",
    gender: "female",
    brand: "Nevenka",
    material: "leather",
    color: "brown",
    newness: "new",
    price: 11000,
    imageUrls: [],
    dateAdded: new Date().getTime(),
    tags: ["Handbags", "Leather bags", "Bags", "Women fashion"],
  },
  {
    id: 2,
    displayName: "Anikulapo",
    sellersId: "3456789",
    phoneNumber: "08152038183",
    headline: "Play Station 4",
    newness: "used",
    sub_category: "games",
    category: "home_appliances",
    price: "200000",
    tags: [
      "Home Appliances",
      "Electronic Gadgets",
      "games",
      "ps",
      "playstation",
      "ps4",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam alias quos blanditiis laborum expedita reprehenderit.",
    imageUrls: [],
    numberOfViews: 4,
    dateAdded: new Date().getTime(),
    transaction_mode: "sell",
  },
  {
    id: 3,
    displayName: "Sandra",
    sellersId: "3456789",
    phoneNumber: "08152038183",
    headline: "iPhone 14 Pro",
    newness: "new",
    backcamera: "23",
    battery: "4000",
    frontcamera: "30",
    brand: "Apple",
    ramsize: "6",
    screensize: "4",
    simslot: "Yes",
    storage: "280",
    color: "Red",
    sub_category: "phoneNumber",
    category: "mobile_devices",
    price: "200000",
    tags: [
      "Mobile Devices",
      "Electronic Gadgets",
      "phone",
      "iphone",
      "apple",
      "pro",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam alias quos blanditiis laborum expedita reprehenderit.",
    imageUrls: [],
    numberOfViews: 276,
    dateAdded: new Date().getTime(),
    transaction_mode: "swap",
  },
  {
    id: 4,
    displayName: "Lauren",
    sellersId: "3456789",
    phoneNumber: "08152038183",
    headline: "Lenovo laptop",
    newness: "foreign used",
    sub_category: "laptop",
    category: "computers",
    ramsize: "6",
    battery: "4000",
    brand: "lenovo",
    screensize: "15",
    price: "350000",
    storage: "280",
    color: "brown",
    tags: ["Computer", "Electronic Gadgets"],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam alias quos blanditiis laborum expedita reprehenderit.",
    imageUrls: [],
    numberOfViews: 1,
    dateAdded: new Date().getTime(),
    transaction_mode: "swap",
  },

  {
    id: 6,
    displayName: "Tunrayo",
    sellersId: "3456789",
    phoneNumber: "08152038183",
    headline: "Play Station 5",
    newness: "used",
    sub_category: "games",
    category: "home_appliances",
    price: "200000",
    tags: ["Home Appliances", "Electronic Gadgets"],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam alias quos blanditiis laborum expedita reprehenderit.",
    imageUrls: [],
    numberOfViews: 4,
    dateAdded: new Date().getTime(),
    transaction_mode: "auction",
  },
  {
    id: 7,
    displayName: "Matthews",
    sellersId: "3456789",
    phoneNumber: "08152038183",
    headline: "iPhone 14 Pro Max",
    newness: "new",
    sub_category: "phoneNumber",
    category: "mobile_devices",
    price: "200000",
    tags: ["Mobile Devices", "Electronic Gadgets"],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam alias quos blanditiis laborum expedita reprehenderit.",
    imageUrls: [],
    numberOfViews: 4,
    dateAdded: new Date().getTime(),
    transaction_mode: "sell",
  },
  {
    id: 8,
    displayName: "Punjay",
    sellersId: "3456789",
    phoneNumber: "08152038183",
    headline: "Asus Zenbook",
    newness: "Tokunbo",
    sub_category: "laptop",
    category: "computers",
    price: "450000",
    ramsize: "6",
    battery: "4000",
    brand: "lenovo",
    screensize: "15",
    storage: "280",
    color: "silver",
    tags: ["Computer", "Electronic Gadgets", "laptop", "lenovo"],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam alias quos blanditiis laborum expedita reprehenderit.",
    imageUrls: [],
    numberOfViews: 4,
    dateAdded: new Date().getTime(),
    transaction_mode: "swap",
  },
  {
    id: 9,
    transaction_mode: "Sell",
    displayName: "Frank",
    category: "books",
    sub_category: "text_book",
    sellersId: "3456789",
    phoneNumber: "08152038183",
    headline: "Keith Moore Anatomy Atlas",
    price: "10000",
    author: "Keith Moore",
    tags: ["Text Books", "Medical Book"],
    imageUrls: [],
    numberOfViews: 418,
    dateAdded: new Date().getTime(),
    newness: "used",
    course_title: "Atlas of the Human Anatomy",
    course_code: "ANT211",
    year_written: new Date().getFullYear(),
  },
  {
    id: 10,
    category: "foods",
    sellersId: "3456789",
    displayName: "Isabella",
    phoneNumber: "08152038183",
    headline: "Egusi Soup",
    sub_category: "soups",
    transaction_mode: "sell",
    price: 550,
    imageUrls: [],
    numberOfViews: 102,
    dateAdded: new Date().getTime(),
    tags: ["food", "soup", "egusi", "swallow"],
  },
  {
    id: 11,
    sellersId: "3456789",
    displayName: "Fisayo",
    phoneNumber: "08152038183",
    numberOfViews: 30,
    transaction_mode: "sell",
    category: "fashion",
    color: "black",
    headline: "Tailor-made Gown",
    sub_category: "dress",
    gender: "female",
    price: 15000,
    size: "L",
    quantity: "5",
    availableColors: ["grey", "black"],
    imageUrls: [],
    newness: "new",
    dateAdded: new Date().getTime(),
    tags: ["Dress", "Fashion"],
  },
  {
    id: 21,
    sellersId: "3456789",
    displayName: "Fisayo",
    phoneNumber: "08152038183",
    numberOfViews: 60,
    transaction_mode: "sell",
    category: "fashion",
    headline: "Office Gown",
    color: "Grey",
    sub_category: "dress",
    gender: "female",
    price: 15500,
    size: "L",
    quantity: "5",
    availableColors: ["grey", "black"],
    imageUrls: [],
    newness: "new",
    dateAdded: new Date().getTime(),
    tags: ["Dress", "Fashion"],
  },
  {
    id: 12,
    sellersId: "3456789",
    displayName: "Ebiye",
    phoneNumber: "08152038183",
    brand: "apple",
    transaction_mode: "sell",
    category: "gadgets",
    headline: "Apple watch",
    sub_category: "smart watch",
    newness: "used",
    price: 50000,
    color: "gold",
    imageUrls: [],
    numberOfViews: 30,
    dateAdded: new Date().getTime(),
    tags: ["smart watch", "smart phoneNumber", "watches", "gadgets"],
  },
  {
    id: 13,
    sellersId: "3456789",
    displayName: "James",
    phoneNumber: "08152038183",
    numberOfViews: 451,
    location: "Ekosodin",
    transaction_mode: "rent",
    category: "real_estate",
    headline: "Selfcon in Ekosodin",
    sub_category: "Self-contained",
    newness: "new",
    amenities: {
      water_in: "Water runs in apertment",
      water_out: "Water runs in the compound",
      electricity: "Has electricity",
      generator: "",
      transformer: "",
      tiled: "Has tiled floors",
      pvc_ceiling: "",
      pop_ceiling: "Has POP ceiling",
    },
    description:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Debitis similique ipsa perspiciatis iusto facilis quis voluptas fugit sint voluptate reiciendis.",
    price: 100000,
    imageUrls: [],
    dateAdded: new Date().getTime(),
    tags: [
      "real estate",
      "houses",
      "rent",
      "apertments",
      "Self-contained",
      "Self-con",
    ],
  },
  {
    id: 14,
    sellersId: "3456789",
    displayName: "Claire",
    phoneNumber: "08152038183",
    numberOfViews: 43,
    transaction_mode: "swap",
    category: "furnitures",
    headline: "Leather Chairs",
    newness: "used",
    set: "4",
    sub_category: "chairs",
    price: 120000,
    imageUrls: [],
    dateAdded: new Date().getTime(),
    tags: ["furniture", "chair"],
  },
  {
    id: 20,
    service: "Shoemaker",
    displayName: "Caleb",
    numberOfViews: 140,
    category: "services",
    headline: "T-Flourish and sons shoes",
    phoneNumber: ["0816789326", "0802736562"],
    location: "Ekosodin",
    address: "30, Edo street, Ekosodin, Ugbowo, Benin City.",
    imageUrls: [],
    dateAdded: new Date().getTime(),
    tags: ["shoes", "shoemaker"],
    rating: 4,
  },
  {
    id: 16,
    displayName: "John",
    numberOfViews: 10,
    category: "services",
    headline: "Chukwudi Gas plant Ltd.",
    service: "Cooking gas",
    phoneNumber: ["0816789326", "0802736562"],
    location: "Ekosodin",
    address: "23, 19th street, BDPA, Ugbowo, Benin City.",
    imageUrls: [],
    dateAdded: new Date().getTime(),
    rating: 4,
    tags: ["gas", "cooking gas"],
  },
  {
    id: 18,
    sellersId: "3456789",
    displayName: "Kyle",
    phoneNumber: "08152038183",
    numberOfViews: 400,
    transaction_mode: "sell",
    category: "fashion",
    color: "blue",
    headline: "valentino T-Shirt",
    gender: "male",
    newness: "new",
    size: "XXL",
    sub_category: "shirt",
    price: 12000,
    imageUrls: [],
    dateAdded: new Date().getTime(),
    tags: ["shirts", "wears", "male", "fashion"],
  },
  {
    id: 19,
    sellersId: "3456789",
    displayName: "Dave",
    phoneNumber: "08152038183",
    numberOfViews: 500,
    transaction_mode: "auction",
    bid: { bidder: "", price: 3000 },
    category: "vehicles",
    headline: "Toyota Camry 2015",
    sub_category: "cars",
    brand: "Toyota",
    model: "Camry",
    color: "red",
    interior: "Leather",
    year: "2015",
    grade: "Tokunbo",
    accidented: "No",
    // price: 6000000,
    imageUrls: [],
    dateAdded: new Date().getTime(),
    tags: ["car", "cars", "toyota"],
  },
  {
    id: 15,
    sellersId: "3456789",
    displayName: "Kelvin",
    phoneNumber: "08152038183",
    numberOfViews: 70,
    transaction_mode: "swap",
    category: "vehicles",
    headline: "Toyota Venza",
    sub_category: "SUV",
    brand: "Toyota",
    model: "venza",
    color: "black",
    interior: "clothe",
    year: "2008",
    grade: "tokunbo",
    accidented: "No",
    price: 6500000,
    imageUrls: [],
    dateAdded: new Date().getTime(),
    tags: [""],
  },
];

export default productsData;
