export const recentProductsData = [
    {
      id: 1,
      displayName: "Victor",
      sellersId: "3456789",
      phoneNumber: "08152038183",
      backcamera: "23",
      battery: "4000",
      brand: "Apple",
      color: "Red",
      frontcamera: "30",
      newness: "new",
      price: "130000",
      headline: "iphone 12 pro max",
      ramsize: "6",
      screensize: "5",
      simslot: "Yes",
      storage: "512",
      sub_category: "phone",
      category: "mobile_devices",
      transaction_mode: "sell",
      imageUrls: [require("../Assets/Images/productImage/iphone14.jpeg")],
      numberOfViews: 374,
      dateAdded: new Date().getTime(),
      tags: ["phone", "iphone", "pro max"],
    },
    {
      id: 35,
      sellersId: "3456789",
      displayName: "Lisa",
      phoneNumber: "08152038183",
      numberOfViews: 670,
      transaction_mode: "sell",
      category: "fashion_accessories",
      headline: "Nevenka Women Leather Handbag",
      sub_category: "Bag",
      gender: "female",
      brand: "Nevenka",
      material: "leather",
      color: "brown",
      newness: "new",
      price: 11000,
      imageUrls: [require("../Assets/Images/productImage/bag.jpeg")],
      dateAdded: new Date().getTime(),
      tags: ["Handbags", "Leather bags", "Bags", "Women fashion"],
    },
    {
      id: 2,
      displayName: "Anikulapo",
      sellersId: "3456789",
      phoneNumber: "08152038183",
      headline: "Play Station 4",
      newness: "used",
      sub_category: "games",
      category: "home_appliances",
      price: "200000",
      tags: [
        "Home Appliances",
        "Electronic Gadgets",
        "games",
        "ps",
        "playstation",
        "ps4",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam alias quos blanditiis laborum expedita reprehenderit.",
      imageUrls: [require("../Assets/Images/productImage/ps40.jpeg")],
      numberOfViews: 4,
      dateAdded: new Date().getTime(),
      transaction_mode: "sell",
    },
    {
      id: 4,
      displayName: "Lauren",
      sellersId: "3456789",
      phoneNumber: "08152038183",
      headline: "Lenovo laptop",
      newness: "foreign used",
      sub_category: "laptop",
      category: "computers",
      ramsize: "6",
      battery: "4000",
      brand: "lenovo",
      screensize: "15",
      price: "350000",
      storage: "280",
      color: "brown",
      tags: ["Computer", "Electronic Gadgets"],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam alias quos blanditiis laborum expedita reprehenderit.",
      imageUrls: [require("../Assets/Images/productImage/lenovo.jpg")],
      numberOfViews: 1,
      dateAdded: new Date().getTime(),
      transaction_mode: "swap",
    },
]  