export const ADD_REQUEST = 'ADD_REQUEST';
export const ADD_REQUEST_SUCCESS = 'ADD_REQUEST_SUCCESS'

export const GET_REQUESTS = 'GET_REQUESTS';
export const GET_REQUESTS_SUCCESS = 'GET_REQUESTS_SUCCESS';

export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_REQUEST_SUCCESS = 'SEARCH_REQUEST_SUCCESS';

export const EDIT_REQUEST = 'EDIT_REQUEST';
export const EDIT_REQUEST_SUCCESS = 'EDIT_REQUEST_SUCCESS';

export const DELETE_REQUEST = 'DELETE_REQUEST';
export const DELETE_REQUEST_SUCCESS = 'DELETE_REQUEST_SUCCESS';

export const ADD_BID = 'ADD_BID'
export const ADD_BID_SUCCESS = 'ADD_BID_SUCCESS'

export const DELETE_BID = 'DELETE_BID'
export const DELETE_BID_SUCCESS = 'DELETE_BID_SUCCESS'

export const GET_RECENT_PRODUCTS = 'GET_RECENT_PRODUCTS';
export const GET_RECENT_PRODUCTS_SUCCESS = 'GET_RECENT_PRODUCTS_SUCCESS';

export const GET_RECENT_AUCTIONS = 'GET_RECENT_AUCTIONS';
export const GET_RECENT_AUCTIONS_SUCCESS = 'GET_RECENT_AUCTIONS_SUCCESS';

export const GET_SINGLE_AUCTIONS = 'GET_SINGLE_AUCTIONS';
export const GET_SINGLE_AUCTIONS_SUCCESS = 'GET_SINGLE_AUCTIONS_SUCCESS';

export const GET_ALL_AUCTIONS = 'GET_ALL_AUCTIONS';
export const GET_ALL_AUCTIONS_SUCCESS = 'GET_ALL_AUCTIONS_SUCCESS';

export const GET_RELETATED_PRODUCTS = 'GET_RELETATED_PRODUCTS';
export const GET_RELETATED_PRODUCTS_SUCCESS = 'GET_RELETATED_PRODUCTS_SUCCESS';

export const GET_RELETATED_AUCTIONS = 'GET_RELETATED_AUCTIONS';
export const GET_RELETATED_AUCTIONS_SUCCESS = 'GET_RELETATED_AUCTIONS_SUCCESS';

export const GET_SELLERS_PRODUCTS = 'GET_SELLERS_PRODUCTS'
export const GET_SELLERS_PRODUCTS_SUCCESS = 'GET_SELLERS_PRODUCTS_SUCCESS'

export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';
export const SEARCH_PRODUCT_SUCCESS = 'SEARCH_PRODUCT_SUCCESS';

export const SEARCH_AUCTIONS = 'SEARCH_AUCTIONS';
export const SEARCH_AUCTIONS_SUCCESS = 'SEARCH_AUCTIONS_SUCCESS';


export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';

export const ADD_AUCTION  = 'ADD_AUCTION'
export const ADD_AUCTION_SUCCESS  = 'ADD_AUCTION_SUCCESS'

export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const REMOVE_PRODUCT_SUCCESS = 'REMOVE_PRODUCT_SUCCESS';

export const REMOVE_AUCTION = 'REMOVE_AUCTION';
export const REMOVE_AUCTION_SUCCESS = 'REMOVE_AUCTION_SUCCESS';

export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS';

export const UPDATE_AUCTION = 'UPDATE_AUCTION';
export const UPDATE_AUCTION_SUCCESS = 'UPDATE_AUCTION_SUCCESS';

export const CANCEL_GET_PRODUCTS = 'CANCEL_GET_PRODUCTS';
export const CANCEL_FETCH_AUCTIONS = 'CANCEL_FETCH_AUCTIONS';
export const CLEAR_SEARCH_STATE = 'CLEAR_SEARCH_STATE';
export const CLEAR_SELLERS_PRODUCT_STATE = 'CLEAR_SELLERS_PRODUCT_STATE';
export const SET_LAST_REF_KEY = 'SET_LAST_REF_KEY';

export const SIGNIN = 'SIGNIN';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNOUT = 'SIGNOUT';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const SIGNIN_FAILURE = "SIGNIN_FAILURE"
export const SIGNOUT_FAILURE = "SIGNOUT_FAILURE"

export const SET_AUTH_STATUS = 'SET_AUTH_STATUS';
export const SIGNIN_WITH_GOOGLE = 'SIGNIN_WITH_GOOGLE';
export const SIGNIN_WITH_FACEBOOK = 'SIGNIN_WITH_FACEBOOK';
export const ON_AUTHSTATE_CHANGED = 'ON_AUTHSTATE_CHANGED';
export const SET_AUTH_PERSISTENCE = 'SET_AUTH_PERSISTENCE';
export const ON_AUTHSTATE_SUCCESS = 'ON_AUTHSTATE_SUCCESS';
export const ON_AUTHSTATE_FAIL = 'ON_AUTHSTATE_FAIL';
export const RESET_PASSWORD = 'RESET_PASSWORD';

export const UPDATE_EMAIL = 'UPDATE_EMAIL';
export const SET_PROFILE = 'SET_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';

export const SET_TEXT_FILTER = 'SET_TEXT_FILTER';
export const SET_BRAND_FILTER = 'SET_BRAND_FILTER';
export const SET_MIN_PRICE_FILTER = 'SET_MIN_PRICE_FILTER';
export const SET_MAX_PRICE_FILTER = 'SET_MAX_PRICE_FILTER';
export const RESET_FILTER = 'RESET_FILTER';
export const APPLY_FILTER = 'APPLY_FILTER';
export const CLEAR_RECENT_SEARCH = 'CLEAR_RECENT_SEARCH';
export const REMOVE_SELECTED_RECENT = 'REMOVE_SELECTED_RECENT';

export const LOADING = 'LOADING';
export const IS_AUTHENTICATING = 'IS_AUTHENTICATING';
export const SET_REQUEST_STATUS = 'SET_REQUEST_STATUS';

export const SET_ALERT = 'SET_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT'